// Auto-generated by Venus AI — allows live preview iframe embedding
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  server: {
    port: 7100,
    host: '0.0.0.0',
    strictPort: true,
    headers: {
      'X-Frame-Options': 'ALLOWALL',
      'Content-Security-Policy': "frame-ancestors *",
    },
    hmr: false,
  },
});
